title: Jiamin Tan # your name (or website title) here
#logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Candidate of <br>
  Master of City Planning + <br>
  Master of Urban Spatial Analytics <br>
  @UPenn <br>
  <br>
  Anticipated graduation date: <br>
  December 2022
  <a href="https://www.linkedin.com/in/jiamin-tan-575b00175/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
